# Clyde 'Thluffy' Sinclair
# SoftDev
# September 2024
# Comments: debug is off, prints "__main__", site says "No hablo queso!"

from flask import Flask
app = Flask(__name__)          # ...

@app.route("/")                # ...
def hello_world():
    print(__name__)            # ...
    return "No hablo queso!"   # ...

app.run()                      # ...
                
